license="MIT"
modLoader="javafml"
loaderVersion="[43.1.3,)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesTraverse/issues"

[[mods]]
modId="dttraverse"
version="${file.jarVersion}"
displayName="Dynamic Trees for Traverse"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Traverse.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-traverse"
logoFile="dtt-logo.png"
credits="Odorousrex for making the original traverse add-on for 1.12.2."
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility for Traverse.
'''

[[dependencies.dttraverse]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="traverse"
    mandatory=true
    versionRange="[7.0.12,)"
    ordering="AFTER"
    side="BOTH"
