license="MIT"
modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesTraverse/issues"

[[mods]]
modId="dttraverse"
version="${file.jarVersion}"
displayName="Dynamic Trees for Traverse"
updateJSONURL="https://github.com/Harleyoc1/DynamicTreesTraverse/blob/1.16.5/version_info.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-traverse"
logoFile="dtt-logo.png"
credits="Odorousrex for making the original traverse add-on for 1.12.2."
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Nature's Aura.
'''

[[dependencies.dttraverse]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0-Beta10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dttraverse]]
    modId="traverse"
    mandatory=true
    versionRange="[0.4.3.8,)"
    ordering="AFTER"
    side="BOTH"
